module.exports = {
  reviewsResponse: [
    {
      _id: '6095f244e19dd6fedc43af96',
      id: 381,
      product_id: 69,
      rating: 3,
      date: '2018-09-18',
      summary: 'Voluptatem corporis debitis harum rerum ipsam fugiat reprehenderit nobis.',
      body: 'Omnis rerum asperiores nobis fuga quis adipisci deleniti et. Incidunt cupiditate sed magni atque. Repellendus quos minima similique quas ad ut. Ipsa provident quasi et perferendis. Dolor et earum nesciunt ipsum. Voluptas excepturi quam voluptas libero omnis aspernatur.',
      recommend: '1',
      reported: '0',
      reviewer_name: 'Daron39',
      reviewer_email: 'Hertha_Fisher47@yahoo.com',
      response: 'Aut laboriosam eligendi.',
      helpfulness: 15,
    },
    {
      _id: '6095f244e19dd6fedc43af97',
      id: 382,
      product_id: 69,
      rating: 5,
      date: '2019-04-15',
      summary: 'Et consequatur vitae veritatis accusamus molestiae voluptas.',
      body: 'Doloribus aut sed nihil. Voluptatem pariatur beatae. Ut recusandae culpa hic optio magni cupiditate blanditiis animi ullam. Maiores veniam perspiciatis voluptatem fugit itaque voluptas sunt eum expedita. Nulla ipsam autem enim aut magnam adipisci et voluptate. Modi perferendis veritatis voluptas est at libero rerum rerum.',
      recommend: '1',
      reported: '0',
      reviewer_name: 'Reuben.Christiansen',
      reviewer_email: 'Retta_Eichmann@yahoo.com',
      response: 'null',
      helpfulness: 15,
    },
    {
      _id: '6095f244e19dd6fedc43af98',
      id: 383,
      product_id: 69,
      rating: 2,
      date: '2018-10-08',
      summary: 'Quos reprehenderit quaerat sint.',
      body: 'Inventore eos id accusantium a et consequatur sed. Impedit quia numquam. Quia ut pariatur vel voluptatum quas soluta sequi. Occaecati id ipsum maxime corrupti mollitia.',
      recommend: '1',
      reported: '0',
      reviewer_name: 'Aileen24',
      reviewer_email: 'Tristian_Keebler@hotmail.com',
      response: 'null',
      helpfulness: 20,
    },
    {
      _id: '6095f244e19dd6fedc43af99',
      id: 384,
      product_id: 69,
      rating: 2,
      date: '2019-03-22',
      summary: 'Esse sit fugiat enim sed modi nobis ipsa enim temporibus.',
      body: 'Architecto unde deserunt. Eius odit qui. Nam ut quia accusantium. Aut aliquid est molestiae minima quidem nostrum amet. Omnis est cupiditate fuga autem iste tenetur fugit. Tempora ea minus dignissimos.',
      recommend: '1',
      reported: '0',
      reviewer_name: 'Bernadine.Stracke',
      reviewer_email: 'Christ.Dickens@yahoo.com',
      response: 'null',
      helpfulness: 23,
    },
    {
      _id: '6095f244e19dd6fedc43af9a',
      id: 385,
      product_id: 69,
      rating: 3,
      date: '2018-11-04',
      summary: 'Eligendi ut possimus omnis a fugit voluptates omnis et.',
      body: 'Et veritatis dolor qui esse illo. Dolorem praesentium ut aliquid. Sed voluptas exercitationem dignissimos doloribus voluptas non consectetur. Magni consequatur illo iste consequuntur dolor doloremque.',
      recommend: '1',
      reported: '0',
      reviewer_name: 'Aletha73',
      reviewer_email: 'Petra4@gmail.com',
      response: 'null',
      helpfulness: 21,
    },
    {
      _id: '6095f244e19dd6fedc43af9b',
      id: 386,
      product_id: 69,
      rating: 2,
      date: '2018-08-28',
      summary: 'Numquam impedit ut eos odit et magnam.',
      body: 'Dolores tempora facilis consequatur doloremque eveniet officia soluta impedit esse. Dolorem sunt quia voluptatum reiciendis. Nemo rerum velit harum aliquam soluta odio iusto perferendis. Et quasi rerum consequuntur vel sed sequi sequi a. Libero cumque omnis incidunt deleniti placeat nemo sint assumenda. Aut in sint est distinctio provident ab omnis omnis.',
      recommend: '1',
      reported: '0',
      reviewer_name: 'Colby.Ondricka61',
      reviewer_email: 'Fabian56@yahoo.com',
      response: 'null',
      helpfulness: 20,
    },
    {
      _id: '6095f244e19dd6fedc43af9c',
      id: 387,
      product_id: 69,
      rating: 3,
      date: '2019-02-17',
      summary: 'Libero aspernatur vitae quia id quia.',
      body: 'Quia sint repellat culpa dolores est minima quia autem. Qui eaque sit. Omnis nostrum rerum voluptas quia amet dolores. Laudantium enim molestias et omnis qui et necessitatibus. Et sed animi qui.',
      recommend: '1',
      reported: '0',
      reviewer_name: 'Roxanne_Stehr58',
      reviewer_email: 'Hank_Donnelly49@yahoo.com',
      response: 'null',
      helpfulness: 19,
    },
    {
      _id: '6095f244e19dd6fedc43af9d',
      id: 388,
      product_id: 69,
      rating: 3,
      date: '2019-07-27',
      summary: 'Et incidunt accusamus sit adipisci.',
      body: 'Aut fugiat earum dolorem explicabo. Culpa facere iure consequatur et placeat. Nostrum veniam omnis vero voluptatem. Ad soluta dolorem. Voluptatem expedita quod molestiae quos hic totam dolore. Dignissimos deserunt perspiciatis aperiam.',
      recommend: '1',
      reported: '1',
      reviewer_name: 'Hans.Harvey18',
      reviewer_email: 'Ike21@gmail.com',
      response: 'null',
      helpfulness: 25,
    },
    {
      _id: '6095f244e19dd6fedc43af9e',
      id: 389,
      product_id: 69,
      rating: 3,
      date: '2019-04-11',
      summary: 'Rem quod voluptates beatae dolores dolorum nam qui expedita.',
      body: 'Id sapiente non vel fuga et voluptas. Omnis consequatur magni. Sit voluptatem enim sunt nulla corrupti dolor voluptatem modi. Debitis quisquam ex labore molestias.',
      recommend: '1',
      reported: '0',
      reviewer_name: 'Danny.Lynch11',
      reviewer_email: 'Selena_Larson@gmail.com',
      response: 'null',
      helpfulness: 16,
    },
    {
      _id: '6095f244e19dd6fedc43af9f',
      id: 390,
      product_id: 69,
      rating: 4,
      date: '2018-10-31',
      summary: 'Dicta est reprehenderit veritatis consequatur ut ex sed.',
      body: 'Rerum rerum rerum enim optio. Vero modi et perferendis praesentium et sed dolorem quasi. Ut quis nisi voluptatem qui dolorum in. Quae consequatur nobis ut veniam quod. Rerum alias omnis et aliquid molestias quia ipsa quia. Occaecati aut praesentium magni aut sit et in dolorem.',
      recommend: '1',
      reported: '0',
      reviewer_name: 'Daisy.Walter12',
      reviewer_email: 'Elnora22@gmail.com',
      response: 'null',
      helpfulness: 20,
    },
    {
      _id: '6095f244e19dd6fedc43afa0',
      id: 391,
      product_id: 69,
      rating: 1,
      date: '2018-10-09',
      summary: 'Voluptatum voluptatibus fuga iure nihil non.',
      body: 'Non tempora est et provident est autem sed. Velit consectetur saepe voluptates. Omnis error ad quo quia corporis. Accusamus porro vel aut et blanditiis explicabo itaque et. Quia et distinctio pariatur ut eum qui molestias et qui.',
      recommend: '0',
      reported: '0',
      reviewer_name: 'Elinore_Bergstrom',
      reviewer_email: 'Henderson.Ortiz@hotmail.com',
      response: 'null',
      helpfulness: 2,
    },
    {
      _id: '6095f244e19dd6fedc43afa1',
      id: 392,
      product_id: 69,
      rating: 1,
      date: '2018-08-05',
      summary: 'Sed facere rerum ut est reprehenderit aspernatur.',
      body: 'Ipsa sunt amet voluptatibus voluptatum. Magnam sint eum nihil sint consequatur beatae accusantium. Nulla possimus ducimus ad omnis. Suscipit cumque dolores autem cum aliquid et voluptates quia.',
      recommend: '0',
      reported: '0',
      reviewer_name: 'Marilie.Funk15',
      reviewer_email: 'Morgan_Bauch@gmail.com',
      response: 'null',
      helpfulness: 18,
    },
    {
      _id: '6095f244e19dd6fedc43afa2',
      id: 393,
      product_id: 69,
      rating: 5,
      date: '2019-05-14',
      summary: 'Consequatur commodi explicabo.',
      body: 'Repudiandae fuga cumque consequatur sed est ipsa est est. Dolor magnam aliquid rerum qui. Et occaecati rerum est ex qui dolorem quis doloremque. Voluptate enim exercitationem sit vel suscipit dignissimos.',
      recommend: '1',
      reported: '0',
      reviewer_name: 'Winfield.Leannon',
      reviewer_email: 'Noemi.Smith@yahoo.com',
      response: 'null',
      helpfulness: 14,
    },
    {
      _id: '6095f244e19dd6fedc43afa3',
      id: 394,
      product_id: 69,
      rating: 5,
      date: '2018-10-12',
      summary: 'Eligendi velit et vero esse ducimus sequi eaque iste.',
      body: 'Ad odit saepe officiis culpa ut id. Ad ea iusto culpa voluptatem aut eum voluptate ea dolores. Quia omnis ipsa laboriosam. Et molestiae inventore aliquid. Saepe ut ipsa.',
      recommend: '1',
      reported: '0',
      reviewer_name: 'Rose_Reilly',
      reviewer_email: 'Carey84@gmail.com',
      response: 'null',
      helpfulness: 15,
    },
  ],
  reviewsPhotosResponse: {
    382: [],
    383: [],
    386: [],
  },
};
